from typing import Any as Any
from pathlib import Path as Path


class OpenSCADObject:
    def __call__(self, *children: OpenSCADObject) -> OpenSCADObject: ...
    def __add__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def __radd__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def __iadd__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def __sub__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def __isub__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def __mul__(self, other: OpenSCADObject) -> OpenSCADObject: ...
    def add(self, child: OpenSCADObject) -> OpenSCADObject: ...
    def set_modifier(self, modifier: str) -> OpenSCADObject: ...


class IncludedOpenSCADObject(OpenSCADObject): ...


def union(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def difference(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def intersection(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def hull(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def minkowski(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def cube(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def sphere(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def cylinder(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def polyhedron(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def circle(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def square(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def polygon(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def text(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def translate(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def rotate(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def scale(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def mirror(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def resize(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def color(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def offset(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def linear_extrude(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def rotate_extrude(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def projection(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def surface(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def render(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def part(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def debug(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def background(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def hole(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def import_scad(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def use(*args: Any, **kwargs: Any) -> Any: ...
def include(*args: Any, **kwargs: Any) -> Any: ...

def scad_render(*args: Any, **kwargs: Any) -> str: ...
def scad_render_to_file(*args: Any, **kwargs: Any) -> str: ...
def scad_render_animated(*args: Any, **kwargs: Any) -> str: ...
def scad_render_animated_file(*args: Any, **kwargs: Any) -> str: ...

def __getattr__(name: str) -> Any: ...
