from typing import Any as Any
from pathlib import Path as Path

from solid import OpenSCADObject as OpenSCADObject

def up(z: float) -> OpenSCADObject: ...
def down(z: float) -> OpenSCADObject: ...
def left(x: float) -> OpenSCADObject: ...
def right(x: float) -> OpenSCADObject: ...
def forward(y: float) -> OpenSCADObject: ...
def back(y: float) -> OpenSCADObject: ...
def translate(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def rotate(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def scale(*args: Any, **kwargs: Any) -> OpenSCADObject: ...
def __getattr__(name: str) -> Any: ...
